# Dependencies
markdown:         kramdown
pygments:         true


# Setup
title:            Y & L
tagline:          'Record our story'

author:
  name:           'Null'
  url:            http://yangliu.love/about/

paginate:         5

# General Jekyll Config
highlighter: rogue
name: Y & L
description: '我爱你，想打张白条给你，上面写着：欠你一生温柔、半世呵护，分期一万年。'
url: "http://yangliu.love/about/"
lsi: false

# Permalinks
permalink:        pretty